<?xml version="1.0" encoding="utf-8"?><Database Name="UOMSDB" Class="UOMSDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=UOMSDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="UOMSDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.b_evaluate_T" Member="b_evaluate_T">
    <Type Name="b_evaluate_T">
      <Column Name="evaluate_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="b_account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="p_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="p_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="p_photo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="p_evaluate" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.b_order_item_T" Member="b_order_item_T">
    <Type Name="b_order_item_T">
      <Column Name="b_o_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="p_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="p_price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="p_num" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.b_order_state_T" Member="b_order_state_T">
    <Type Name="b_order_state_T">
      <Column Name="b_o_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="b_o_state" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="b_o_subTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.b_order_T" Member="b_order_T">
    <Type Name="b_order_T">
      <Column Name="b_o_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="b_account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_storeName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="b_orderState" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="b_o_totalPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="b_o_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.buyer_T" Member="buyer_T">
    <Type Name="buyer_T">
      <Column Name="b_account" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="b_password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="b_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="b_tel" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="b_balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="b_question" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="b_answer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="b_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.cart_T" Member="cart_T">
    <Type Name="cart_T">
      <Column Name="b_account" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="s_account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_storeName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="p_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="p_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="p_price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="p_num" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.product_T" Member="product_T">
    <Type Name="product_T">
      <Column Name="p_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="s_account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="p_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="p_category" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="p_price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="p_cNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="p_photo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="p_saleNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.s_order_item_T" Member="s_order_item_T">
    <Type Name="s_order_item_T">
      <Column Name="s_o_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="p_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="p_price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="p_num" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.s_order_T" Member="s_order_T">
    <Type Name="s_order_T">
      <Column Name="s_o_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="b_account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_o_state" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="s_o_totalprice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="s_o_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.seller_T" Member="seller_T">
    <Type Name="seller_T">
      <Column Name="s_account" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="s_password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_storeName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_tel" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="s_question" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_answer" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="s_state" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="s_profit" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>