#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UOMSDB")]
	public partial class UOMSDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertb_evaluate_T(b_evaluate_T instance);
    partial void Updateb_evaluate_T(b_evaluate_T instance);
    partial void Deleteb_evaluate_T(b_evaluate_T instance);
    partial void Insertb_order_item_T(b_order_item_T instance);
    partial void Updateb_order_item_T(b_order_item_T instance);
    partial void Deleteb_order_item_T(b_order_item_T instance);
    partial void Insertb_order_state_T(b_order_state_T instance);
    partial void Updateb_order_state_T(b_order_state_T instance);
    partial void Deleteb_order_state_T(b_order_state_T instance);
    partial void Insertb_order_T(b_order_T instance);
    partial void Updateb_order_T(b_order_T instance);
    partial void Deleteb_order_T(b_order_T instance);
    partial void Insertbuyer_T(buyer_T instance);
    partial void Updatebuyer_T(buyer_T instance);
    partial void Deletebuyer_T(buyer_T instance);
    partial void Insertcart_T(cart_T instance);
    partial void Updatecart_T(cart_T instance);
    partial void Deletecart_T(cart_T instance);
    partial void Insertproduct_T(product_T instance);
    partial void Updateproduct_T(product_T instance);
    partial void Deleteproduct_T(product_T instance);
    partial void Inserts_order_item_T(s_order_item_T instance);
    partial void Updates_order_item_T(s_order_item_T instance);
    partial void Deletes_order_item_T(s_order_item_T instance);
    partial void Inserts_order_T(s_order_T instance);
    partial void Updates_order_T(s_order_T instance);
    partial void Deletes_order_T(s_order_T instance);
    partial void Insertseller_T(seller_T instance);
    partial void Updateseller_T(seller_T instance);
    partial void Deleteseller_T(seller_T instance);
    #endregion
		
		public UOMSDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["UOMSDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UOMSDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UOMSDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UOMSDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UOMSDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<b_evaluate_T> b_evaluate_T
		{
			get
			{
				return this.GetTable<b_evaluate_T>();
			}
		}
		
		public System.Data.Linq.Table<b_order_item_T> b_order_item_T
		{
			get
			{
				return this.GetTable<b_order_item_T>();
			}
		}
		
		public System.Data.Linq.Table<b_order_state_T> b_order_state_T
		{
			get
			{
				return this.GetTable<b_order_state_T>();
			}
		}
		
		public System.Data.Linq.Table<b_order_T> b_order_T
		{
			get
			{
				return this.GetTable<b_order_T>();
			}
		}
		
		public System.Data.Linq.Table<buyer_T> buyer_T
		{
			get
			{
				return this.GetTable<buyer_T>();
			}
		}
		
		public System.Data.Linq.Table<cart_T> cart_T
		{
			get
			{
				return this.GetTable<cart_T>();
			}
		}
		
		public System.Data.Linq.Table<product_T> product_T
		{
			get
			{
				return this.GetTable<product_T>();
			}
		}
		
		public System.Data.Linq.Table<s_order_item_T> s_order_item_T
		{
			get
			{
				return this.GetTable<s_order_item_T>();
			}
		}
		
		public System.Data.Linq.Table<s_order_T> s_order_T
		{
			get
			{
				return this.GetTable<s_order_T>();
			}
		}
		
		public System.Data.Linq.Table<seller_T> seller_T
		{
			get
			{
				return this.GetTable<seller_T>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.b_evaluate_T")]
	public partial class b_evaluate_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _evaluate_Id;
		
		private string _b_account;
		
		private int _p_Id;
		
		private string _p_name;
		
		private string _p_photo;
		
		private string _p_evaluate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onevaluate_IdChanging(int value);
    partial void Onevaluate_IdChanged();
    partial void Onb_accountChanging(string value);
    partial void Onb_accountChanged();
    partial void Onp_IdChanging(int value);
    partial void Onp_IdChanged();
    partial void Onp_nameChanging(string value);
    partial void Onp_nameChanged();
    partial void Onp_photoChanging(string value);
    partial void Onp_photoChanged();
    partial void Onp_evaluateChanging(string value);
    partial void Onp_evaluateChanged();
    #endregion
		
		public b_evaluate_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaluate_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int evaluate_Id
		{
			get
			{
				return this._evaluate_Id;
			}
			set
			{
				if ((this._evaluate_Id != value))
				{
					this.Onevaluate_IdChanging(value);
					this.SendPropertyChanging();
					this._evaluate_Id = value;
					this.SendPropertyChanged("evaluate_Id");
					this.Onevaluate_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_account", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string b_account
		{
			get
			{
				return this._b_account;
			}
			set
			{
				if ((this._b_account != value))
				{
					this.Onb_accountChanging(value);
					this.SendPropertyChanging();
					this._b_account = value;
					this.SendPropertyChanged("b_account");
					this.Onb_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_Id", DbType="Int NOT NULL")]
		public int p_Id
		{
			get
			{
				return this._p_Id;
			}
			set
			{
				if ((this._p_Id != value))
				{
					this.Onp_IdChanging(value);
					this.SendPropertyChanging();
					this._p_Id = value;
					this.SendPropertyChanged("p_Id");
					this.Onp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string p_name
		{
			get
			{
				return this._p_name;
			}
			set
			{
				if ((this._p_name != value))
				{
					this.Onp_nameChanging(value);
					this.SendPropertyChanging();
					this._p_name = value;
					this.SendPropertyChanged("p_name");
					this.Onp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_photo", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string p_photo
		{
			get
			{
				return this._p_photo;
			}
			set
			{
				if ((this._p_photo != value))
				{
					this.Onp_photoChanging(value);
					this.SendPropertyChanging();
					this._p_photo = value;
					this.SendPropertyChanged("p_photo");
					this.Onp_photoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_evaluate", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string p_evaluate
		{
			get
			{
				return this._p_evaluate;
			}
			set
			{
				if ((this._p_evaluate != value))
				{
					this.Onp_evaluateChanging(value);
					this.SendPropertyChanging();
					this._p_evaluate = value;
					this.SendPropertyChanged("p_evaluate");
					this.Onp_evaluateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.b_order_item_T")]
	public partial class b_order_item_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _b_o_Id;
		
		private int _p_Id;
		
		private decimal _p_price;
		
		private int _p_num;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onb_o_IdChanging(int value);
    partial void Onb_o_IdChanged();
    partial void Onp_IdChanging(int value);
    partial void Onp_IdChanged();
    partial void Onp_priceChanging(decimal value);
    partial void Onp_priceChanged();
    partial void Onp_numChanging(int value);
    partial void Onp_numChanged();
    #endregion
		
		public b_order_item_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_o_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int b_o_Id
		{
			get
			{
				return this._b_o_Id;
			}
			set
			{
				if ((this._b_o_Id != value))
				{
					this.Onb_o_IdChanging(value);
					this.SendPropertyChanging();
					this._b_o_Id = value;
					this.SendPropertyChanged("b_o_Id");
					this.Onb_o_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_Id", DbType="Int NOT NULL")]
		public int p_Id
		{
			get
			{
				return this._p_Id;
			}
			set
			{
				if ((this._p_Id != value))
				{
					this.Onp_IdChanging(value);
					this.SendPropertyChanging();
					this._p_Id = value;
					this.SendPropertyChanged("p_Id");
					this.Onp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_price", DbType="Money NOT NULL")]
		public decimal p_price
		{
			get
			{
				return this._p_price;
			}
			set
			{
				if ((this._p_price != value))
				{
					this.Onp_priceChanging(value);
					this.SendPropertyChanging();
					this._p_price = value;
					this.SendPropertyChanged("p_price");
					this.Onp_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_num", DbType="Int NOT NULL")]
		public int p_num
		{
			get
			{
				return this._p_num;
			}
			set
			{
				if ((this._p_num != value))
				{
					this.Onp_numChanging(value);
					this.SendPropertyChanging();
					this._p_num = value;
					this.SendPropertyChanged("p_num");
					this.Onp_numChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.b_order_state_T")]
	public partial class b_order_state_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _b_o_Id;
		
		private string _b_o_state;
		
		private System.DateTime _b_o_subTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onb_o_IdChanging(int value);
    partial void Onb_o_IdChanged();
    partial void Onb_o_stateChanging(string value);
    partial void Onb_o_stateChanged();
    partial void Onb_o_subTimeChanging(System.DateTime value);
    partial void Onb_o_subTimeChanged();
    #endregion
		
		public b_order_state_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_o_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int b_o_Id
		{
			get
			{
				return this._b_o_Id;
			}
			set
			{
				if ((this._b_o_Id != value))
				{
					this.Onb_o_IdChanging(value);
					this.SendPropertyChanging();
					this._b_o_Id = value;
					this.SendPropertyChanged("b_o_Id");
					this.Onb_o_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_o_state", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string b_o_state
		{
			get
			{
				return this._b_o_state;
			}
			set
			{
				if ((this._b_o_state != value))
				{
					this.Onb_o_stateChanging(value);
					this.SendPropertyChanging();
					this._b_o_state = value;
					this.SendPropertyChanged("b_o_state");
					this.Onb_o_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_o_subTime", DbType="DateTime NOT NULL")]
		public System.DateTime b_o_subTime
		{
			get
			{
				return this._b_o_subTime;
			}
			set
			{
				if ((this._b_o_subTime != value))
				{
					this.Onb_o_subTimeChanging(value);
					this.SendPropertyChanging();
					this._b_o_subTime = value;
					this.SendPropertyChanged("b_o_subTime");
					this.Onb_o_subTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.b_order_T")]
	public partial class b_order_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _b_o_Id;
		
		private string _b_account;
		
		private string _s_account;
		
		private string _s_storeName;
		
		private string _b_orderState;
		
		private decimal _b_o_totalPrice;
		
		private System.DateTime _b_o_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onb_o_IdChanging(int value);
    partial void Onb_o_IdChanged();
    partial void Onb_accountChanging(string value);
    partial void Onb_accountChanged();
    partial void Ons_accountChanging(string value);
    partial void Ons_accountChanged();
    partial void Ons_storeNameChanging(string value);
    partial void Ons_storeNameChanged();
    partial void Onb_orderStateChanging(string value);
    partial void Onb_orderStateChanged();
    partial void Onb_o_totalPriceChanging(decimal value);
    partial void Onb_o_totalPriceChanged();
    partial void Onb_o_timeChanging(System.DateTime value);
    partial void Onb_o_timeChanged();
    #endregion
		
		public b_order_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_o_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int b_o_Id
		{
			get
			{
				return this._b_o_Id;
			}
			set
			{
				if ((this._b_o_Id != value))
				{
					this.Onb_o_IdChanging(value);
					this.SendPropertyChanging();
					this._b_o_Id = value;
					this.SendPropertyChanged("b_o_Id");
					this.Onb_o_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_account", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string b_account
		{
			get
			{
				return this._b_account;
			}
			set
			{
				if ((this._b_account != value))
				{
					this.Onb_accountChanging(value);
					this.SendPropertyChanging();
					this._b_account = value;
					this.SendPropertyChanged("b_account");
					this.Onb_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_account", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_account
		{
			get
			{
				return this._s_account;
			}
			set
			{
				if ((this._s_account != value))
				{
					this.Ons_accountChanging(value);
					this.SendPropertyChanging();
					this._s_account = value;
					this.SendPropertyChanged("s_account");
					this.Ons_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_storeName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_storeName
		{
			get
			{
				return this._s_storeName;
			}
			set
			{
				if ((this._s_storeName != value))
				{
					this.Ons_storeNameChanging(value);
					this.SendPropertyChanging();
					this._s_storeName = value;
					this.SendPropertyChanged("s_storeName");
					this.Ons_storeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_orderState", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string b_orderState
		{
			get
			{
				return this._b_orderState;
			}
			set
			{
				if ((this._b_orderState != value))
				{
					this.Onb_orderStateChanging(value);
					this.SendPropertyChanging();
					this._b_orderState = value;
					this.SendPropertyChanged("b_orderState");
					this.Onb_orderStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_o_totalPrice", DbType="Money NOT NULL")]
		public decimal b_o_totalPrice
		{
			get
			{
				return this._b_o_totalPrice;
			}
			set
			{
				if ((this._b_o_totalPrice != value))
				{
					this.Onb_o_totalPriceChanging(value);
					this.SendPropertyChanging();
					this._b_o_totalPrice = value;
					this.SendPropertyChanged("b_o_totalPrice");
					this.Onb_o_totalPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_o_time", DbType="DateTime NOT NULL")]
		public System.DateTime b_o_time
		{
			get
			{
				return this._b_o_time;
			}
			set
			{
				if ((this._b_o_time != value))
				{
					this.Onb_o_timeChanging(value);
					this.SendPropertyChanging();
					this._b_o_time = value;
					this.SendPropertyChanged("b_o_time");
					this.Onb_o_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.buyer_T")]
	public partial class buyer_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _b_account;
		
		private string _b_password;
		
		private string _b_name;
		
		private string _b_tel;
		
		private decimal _b_balance;
		
		private string _b_question;
		
		private string _b_answer;
		
		private string _b_email;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onb_accountChanging(string value);
    partial void Onb_accountChanged();
    partial void Onb_passwordChanging(string value);
    partial void Onb_passwordChanged();
    partial void Onb_nameChanging(string value);
    partial void Onb_nameChanged();
    partial void Onb_telChanging(string value);
    partial void Onb_telChanged();
    partial void Onb_balanceChanging(decimal value);
    partial void Onb_balanceChanged();
    partial void Onb_questionChanging(string value);
    partial void Onb_questionChanged();
    partial void Onb_answerChanging(string value);
    partial void Onb_answerChanged();
    partial void Onb_emailChanging(string value);
    partial void Onb_emailChanged();
    #endregion
		
		public buyer_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_account", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string b_account
		{
			get
			{
				return this._b_account;
			}
			set
			{
				if ((this._b_account != value))
				{
					this.Onb_accountChanging(value);
					this.SendPropertyChanging();
					this._b_account = value;
					this.SendPropertyChanged("b_account");
					this.Onb_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string b_password
		{
			get
			{
				return this._b_password;
			}
			set
			{
				if ((this._b_password != value))
				{
					this.Onb_passwordChanging(value);
					this.SendPropertyChanging();
					this._b_password = value;
					this.SendPropertyChanged("b_password");
					this.Onb_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string b_name
		{
			get
			{
				return this._b_name;
			}
			set
			{
				if ((this._b_name != value))
				{
					this.Onb_nameChanging(value);
					this.SendPropertyChanging();
					this._b_name = value;
					this.SendPropertyChanged("b_name");
					this.Onb_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_tel", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string b_tel
		{
			get
			{
				return this._b_tel;
			}
			set
			{
				if ((this._b_tel != value))
				{
					this.Onb_telChanging(value);
					this.SendPropertyChanging();
					this._b_tel = value;
					this.SendPropertyChanged("b_tel");
					this.Onb_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_balance", DbType="Money NOT NULL")]
		public decimal b_balance
		{
			get
			{
				return this._b_balance;
			}
			set
			{
				if ((this._b_balance != value))
				{
					this.Onb_balanceChanging(value);
					this.SendPropertyChanging();
					this._b_balance = value;
					this.SendPropertyChanged("b_balance");
					this.Onb_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_question", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string b_question
		{
			get
			{
				return this._b_question;
			}
			set
			{
				if ((this._b_question != value))
				{
					this.Onb_questionChanging(value);
					this.SendPropertyChanging();
					this._b_question = value;
					this.SendPropertyChanged("b_question");
					this.Onb_questionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_answer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string b_answer
		{
			get
			{
				return this._b_answer;
			}
			set
			{
				if ((this._b_answer != value))
				{
					this.Onb_answerChanging(value);
					this.SendPropertyChanging();
					this._b_answer = value;
					this.SendPropertyChanged("b_answer");
					this.Onb_answerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string b_email
		{
			get
			{
				return this._b_email;
			}
			set
			{
				if ((this._b_email != value))
				{
					this.Onb_emailChanging(value);
					this.SendPropertyChanging();
					this._b_email = value;
					this.SendPropertyChanged("b_email");
					this.Onb_emailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cart_T")]
	public partial class cart_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _b_account;
		
		private string _s_account;
		
		private string _s_storeName;
		
		private int _p_Id;
		
		private string _p_name;
		
		private decimal _p_price;
		
		private int _p_num;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onb_accountChanging(string value);
    partial void Onb_accountChanged();
    partial void Ons_accountChanging(string value);
    partial void Ons_accountChanged();
    partial void Ons_storeNameChanging(string value);
    partial void Ons_storeNameChanged();
    partial void Onp_IdChanging(int value);
    partial void Onp_IdChanged();
    partial void Onp_nameChanging(string value);
    partial void Onp_nameChanged();
    partial void Onp_priceChanging(decimal value);
    partial void Onp_priceChanged();
    partial void Onp_numChanging(int value);
    partial void Onp_numChanged();
    #endregion
		
		public cart_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_account", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string b_account
		{
			get
			{
				return this._b_account;
			}
			set
			{
				if ((this._b_account != value))
				{
					this.Onb_accountChanging(value);
					this.SendPropertyChanging();
					this._b_account = value;
					this.SendPropertyChanged("b_account");
					this.Onb_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_account", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_account
		{
			get
			{
				return this._s_account;
			}
			set
			{
				if ((this._s_account != value))
				{
					this.Ons_accountChanging(value);
					this.SendPropertyChanging();
					this._s_account = value;
					this.SendPropertyChanged("s_account");
					this.Ons_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_storeName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_storeName
		{
			get
			{
				return this._s_storeName;
			}
			set
			{
				if ((this._s_storeName != value))
				{
					this.Ons_storeNameChanging(value);
					this.SendPropertyChanging();
					this._s_storeName = value;
					this.SendPropertyChanged("s_storeName");
					this.Ons_storeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int p_Id
		{
			get
			{
				return this._p_Id;
			}
			set
			{
				if ((this._p_Id != value))
				{
					this.Onp_IdChanging(value);
					this.SendPropertyChanging();
					this._p_Id = value;
					this.SendPropertyChanged("p_Id");
					this.Onp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string p_name
		{
			get
			{
				return this._p_name;
			}
			set
			{
				if ((this._p_name != value))
				{
					this.Onp_nameChanging(value);
					this.SendPropertyChanging();
					this._p_name = value;
					this.SendPropertyChanged("p_name");
					this.Onp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_price", DbType="Money NOT NULL")]
		public decimal p_price
		{
			get
			{
				return this._p_price;
			}
			set
			{
				if ((this._p_price != value))
				{
					this.Onp_priceChanging(value);
					this.SendPropertyChanging();
					this._p_price = value;
					this.SendPropertyChanged("p_price");
					this.Onp_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_num", DbType="Int NOT NULL")]
		public int p_num
		{
			get
			{
				return this._p_num;
			}
			set
			{
				if ((this._p_num != value))
				{
					this.Onp_numChanging(value);
					this.SendPropertyChanging();
					this._p_num = value;
					this.SendPropertyChanged("p_num");
					this.Onp_numChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_T")]
	public partial class product_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _p_Id;
		
		private string _s_account;
		
		private string _p_name;
		
		private string _p_category;
		
		private decimal _p_price;
		
		private int _p_cNum;
		
		private string _p_photo;
		
		private int _p_saleNum;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onp_IdChanging(int value);
    partial void Onp_IdChanged();
    partial void Ons_accountChanging(string value);
    partial void Ons_accountChanged();
    partial void Onp_nameChanging(string value);
    partial void Onp_nameChanged();
    partial void Onp_categoryChanging(string value);
    partial void Onp_categoryChanged();
    partial void Onp_priceChanging(decimal value);
    partial void Onp_priceChanged();
    partial void Onp_cNumChanging(int value);
    partial void Onp_cNumChanged();
    partial void Onp_photoChanging(string value);
    partial void Onp_photoChanged();
    partial void Onp_saleNumChanging(int value);
    partial void Onp_saleNumChanged();
    #endregion
		
		public product_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int p_Id
		{
			get
			{
				return this._p_Id;
			}
			set
			{
				if ((this._p_Id != value))
				{
					this.Onp_IdChanging(value);
					this.SendPropertyChanging();
					this._p_Id = value;
					this.SendPropertyChanged("p_Id");
					this.Onp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_account", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_account
		{
			get
			{
				return this._s_account;
			}
			set
			{
				if ((this._s_account != value))
				{
					this.Ons_accountChanging(value);
					this.SendPropertyChanging();
					this._s_account = value;
					this.SendPropertyChanged("s_account");
					this.Ons_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string p_name
		{
			get
			{
				return this._p_name;
			}
			set
			{
				if ((this._p_name != value))
				{
					this.Onp_nameChanging(value);
					this.SendPropertyChanging();
					this._p_name = value;
					this.SendPropertyChanged("p_name");
					this.Onp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_category", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string p_category
		{
			get
			{
				return this._p_category;
			}
			set
			{
				if ((this._p_category != value))
				{
					this.Onp_categoryChanging(value);
					this.SendPropertyChanging();
					this._p_category = value;
					this.SendPropertyChanged("p_category");
					this.Onp_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_price", DbType="Money NOT NULL")]
		public decimal p_price
		{
			get
			{
				return this._p_price;
			}
			set
			{
				if ((this._p_price != value))
				{
					this.Onp_priceChanging(value);
					this.SendPropertyChanging();
					this._p_price = value;
					this.SendPropertyChanged("p_price");
					this.Onp_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_cNum", DbType="Int NOT NULL")]
		public int p_cNum
		{
			get
			{
				return this._p_cNum;
			}
			set
			{
				if ((this._p_cNum != value))
				{
					this.Onp_cNumChanging(value);
					this.SendPropertyChanging();
					this._p_cNum = value;
					this.SendPropertyChanged("p_cNum");
					this.Onp_cNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_photo", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string p_photo
		{
			get
			{
				return this._p_photo;
			}
			set
			{
				if ((this._p_photo != value))
				{
					this.Onp_photoChanging(value);
					this.SendPropertyChanging();
					this._p_photo = value;
					this.SendPropertyChanged("p_photo");
					this.Onp_photoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_saleNum", DbType="Int NOT NULL")]
		public int p_saleNum
		{
			get
			{
				return this._p_saleNum;
			}
			set
			{
				if ((this._p_saleNum != value))
				{
					this.Onp_saleNumChanging(value);
					this.SendPropertyChanging();
					this._p_saleNum = value;
					this.SendPropertyChanged("p_saleNum");
					this.Onp_saleNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.s_order_item_T")]
	public partial class s_order_item_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _s_o_Id;
		
		private int _p_Id;
		
		private decimal _p_price;
		
		private int _p_num;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ons_o_IdChanging(int value);
    partial void Ons_o_IdChanged();
    partial void Onp_IdChanging(int value);
    partial void Onp_IdChanged();
    partial void Onp_priceChanging(decimal value);
    partial void Onp_priceChanged();
    partial void Onp_numChanging(int value);
    partial void Onp_numChanged();
    #endregion
		
		public s_order_item_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_o_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int s_o_Id
		{
			get
			{
				return this._s_o_Id;
			}
			set
			{
				if ((this._s_o_Id != value))
				{
					this.Ons_o_IdChanging(value);
					this.SendPropertyChanging();
					this._s_o_Id = value;
					this.SendPropertyChanged("s_o_Id");
					this.Ons_o_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_Id", DbType="Int NOT NULL")]
		public int p_Id
		{
			get
			{
				return this._p_Id;
			}
			set
			{
				if ((this._p_Id != value))
				{
					this.Onp_IdChanging(value);
					this.SendPropertyChanging();
					this._p_Id = value;
					this.SendPropertyChanged("p_Id");
					this.Onp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_price", DbType="Money NOT NULL")]
		public decimal p_price
		{
			get
			{
				return this._p_price;
			}
			set
			{
				if ((this._p_price != value))
				{
					this.Onp_priceChanging(value);
					this.SendPropertyChanging();
					this._p_price = value;
					this.SendPropertyChanged("p_price");
					this.Onp_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_num", DbType="Int NOT NULL")]
		public int p_num
		{
			get
			{
				return this._p_num;
			}
			set
			{
				if ((this._p_num != value))
				{
					this.Onp_numChanging(value);
					this.SendPropertyChanging();
					this._p_num = value;
					this.SendPropertyChanged("p_num");
					this.Onp_numChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.s_order_T")]
	public partial class s_order_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _s_o_Id;
		
		private string _b_account;
		
		private string _s_account;
		
		private string _s_o_state;
		
		private decimal _s_o_totalprice;
		
		private System.DateTime _s_o_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ons_o_IdChanging(int value);
    partial void Ons_o_IdChanged();
    partial void Onb_accountChanging(string value);
    partial void Onb_accountChanged();
    partial void Ons_accountChanging(string value);
    partial void Ons_accountChanged();
    partial void Ons_o_stateChanging(string value);
    partial void Ons_o_stateChanged();
    partial void Ons_o_totalpriceChanging(decimal value);
    partial void Ons_o_totalpriceChanged();
    partial void Ons_o_timeChanging(System.DateTime value);
    partial void Ons_o_timeChanged();
    #endregion
		
		public s_order_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_o_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int s_o_Id
		{
			get
			{
				return this._s_o_Id;
			}
			set
			{
				if ((this._s_o_Id != value))
				{
					this.Ons_o_IdChanging(value);
					this.SendPropertyChanging();
					this._s_o_Id = value;
					this.SendPropertyChanged("s_o_Id");
					this.Ons_o_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_account", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string b_account
		{
			get
			{
				return this._b_account;
			}
			set
			{
				if ((this._b_account != value))
				{
					this.Onb_accountChanging(value);
					this.SendPropertyChanging();
					this._b_account = value;
					this.SendPropertyChanged("b_account");
					this.Onb_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_account", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_account
		{
			get
			{
				return this._s_account;
			}
			set
			{
				if ((this._s_account != value))
				{
					this.Ons_accountChanging(value);
					this.SendPropertyChanging();
					this._s_account = value;
					this.SendPropertyChanged("s_account");
					this.Ons_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_o_state", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string s_o_state
		{
			get
			{
				return this._s_o_state;
			}
			set
			{
				if ((this._s_o_state != value))
				{
					this.Ons_o_stateChanging(value);
					this.SendPropertyChanging();
					this._s_o_state = value;
					this.SendPropertyChanged("s_o_state");
					this.Ons_o_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_o_totalprice", DbType="Money NOT NULL")]
		public decimal s_o_totalprice
		{
			get
			{
				return this._s_o_totalprice;
			}
			set
			{
				if ((this._s_o_totalprice != value))
				{
					this.Ons_o_totalpriceChanging(value);
					this.SendPropertyChanging();
					this._s_o_totalprice = value;
					this.SendPropertyChanged("s_o_totalprice");
					this.Ons_o_totalpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_o_time", DbType="DateTime NOT NULL")]
		public System.DateTime s_o_time
		{
			get
			{
				return this._s_o_time;
			}
			set
			{
				if ((this._s_o_time != value))
				{
					this.Ons_o_timeChanging(value);
					this.SendPropertyChanging();
					this._s_o_time = value;
					this.SendPropertyChanged("s_o_time");
					this.Ons_o_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.seller_T")]
	public partial class seller_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _s_account;
		
		private string _s_password;
		
		private string _s_storeName;
		
		private string _s_name;
		
		private string _s_tel;
		
		private string _s_question;
		
		private string _s_answer;
		
		private bool _s_state;
		
		private decimal _s_profit;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ons_accountChanging(string value);
    partial void Ons_accountChanged();
    partial void Ons_passwordChanging(string value);
    partial void Ons_passwordChanged();
    partial void Ons_storeNameChanging(string value);
    partial void Ons_storeNameChanged();
    partial void Ons_nameChanging(string value);
    partial void Ons_nameChanged();
    partial void Ons_telChanging(string value);
    partial void Ons_telChanged();
    partial void Ons_questionChanging(string value);
    partial void Ons_questionChanged();
    partial void Ons_answerChanging(string value);
    partial void Ons_answerChanged();
    partial void Ons_stateChanging(bool value);
    partial void Ons_stateChanged();
    partial void Ons_profitChanging(decimal value);
    partial void Ons_profitChanged();
    #endregion
		
		public seller_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_account", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string s_account
		{
			get
			{
				return this._s_account;
			}
			set
			{
				if ((this._s_account != value))
				{
					this.Ons_accountChanging(value);
					this.SendPropertyChanging();
					this._s_account = value;
					this.SendPropertyChanged("s_account");
					this.Ons_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_password
		{
			get
			{
				return this._s_password;
			}
			set
			{
				if ((this._s_password != value))
				{
					this.Ons_passwordChanging(value);
					this.SendPropertyChanging();
					this._s_password = value;
					this.SendPropertyChanged("s_password");
					this.Ons_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_storeName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_storeName
		{
			get
			{
				return this._s_storeName;
			}
			set
			{
				if ((this._s_storeName != value))
				{
					this.Ons_storeNameChanging(value);
					this.SendPropertyChanging();
					this._s_storeName = value;
					this.SendPropertyChanged("s_storeName");
					this.Ons_storeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_name
		{
			get
			{
				return this._s_name;
			}
			set
			{
				if ((this._s_name != value))
				{
					this.Ons_nameChanging(value);
					this.SendPropertyChanging();
					this._s_name = value;
					this.SendPropertyChanged("s_name");
					this.Ons_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_tel", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string s_tel
		{
			get
			{
				return this._s_tel;
			}
			set
			{
				if ((this._s_tel != value))
				{
					this.Ons_telChanging(value);
					this.SendPropertyChanging();
					this._s_tel = value;
					this.SendPropertyChanged("s_tel");
					this.Ons_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_question", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_question
		{
			get
			{
				return this._s_question;
			}
			set
			{
				if ((this._s_question != value))
				{
					this.Ons_questionChanging(value);
					this.SendPropertyChanging();
					this._s_question = value;
					this.SendPropertyChanged("s_question");
					this.Ons_questionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_answer", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string s_answer
		{
			get
			{
				return this._s_answer;
			}
			set
			{
				if ((this._s_answer != value))
				{
					this.Ons_answerChanging(value);
					this.SendPropertyChanging();
					this._s_answer = value;
					this.SendPropertyChanged("s_answer");
					this.Ons_answerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_state", DbType="Bit NOT NULL")]
		public bool s_state
		{
			get
			{
				return this._s_state;
			}
			set
			{
				if ((this._s_state != value))
				{
					this.Ons_stateChanging(value);
					this.SendPropertyChanging();
					this._s_state = value;
					this.SendPropertyChanged("s_state");
					this.Ons_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_profit", DbType="Money NOT NULL")]
		public decimal s_profit
		{
			get
			{
				return this._s_profit;
			}
			set
			{
				if ((this._s_profit != value))
				{
					this.Ons_profitChanging(value);
					this.SendPropertyChanging();
					this._s_profit = value;
					this.SendPropertyChanged("s_profit");
					this.Ons_profitChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
